quote(c, "#include \"../c/atom.h\"")

typedef [int32] unsigned long pred_t;
quote(MLMLI, "type pred = pred_t");

typedef struct {
  [int32] unsigned long pid;
  [int64,mlname(value)] unsigned long val;
} atom;
quote(MLMLI, "type t = atom");

atom neg(atom at);

quote(MLI, "val at_True : atom");
quote(ML, "let at_True = { pid = Int32.zero ; value = Int64.zero }");
quote(MLI, "val at_False : atom");
quote(ML, "let at_False = neg at_True");
