quote(c, "#include \"c/builtins.h\"");

import "atom.idl";
import "solver.idl";

/* These return false on top-level failure. */
// boolean clause([in] solver s, [in,size_is(sz)] atom cl[], int sz);

typedef struct {
  [mlname(ic)] int c;
  [mlname(ix)] intvar x; 
} int_linterm;

typedef struct {
  [mlname(ac)] int c;
  [mlname(ax)] atom x; 
} at_linterm;

// These are half-reified.
// For strict versions, call with r = at_True
boolean linear_le([in] solver s, atom r, [in,size_is(sz)] int_linterm ts[], int sz, int k);
boolean linear_ne([in] solver s, atom r, [in,size_is(sz)] int_linterm ts[], int sz, int k);
boolean atmost_1([in] solver s, atom r, [in,size_is(sz)] atom xs[], int sz);
boolean atmost_k([in] solver s, atom r, [in,size_is(sz)] atom xs[], int sz, int k);

boolean bool_linear_le([in] solver s, atom r, [in,size_is(sz)] at_linterm ts[], int sz, int k);
boolean bool_linear_ne([in] solver s, atom r, [in,size_is(sz)] at_linterm ts[], int sz, int k);

boolean int_mul([in] solver s, atom r, intvar z, intvar x, intvar y);
boolean int_div([in] solver s, atom r, intvar z, intvar x, intvar y);
boolean int_abs([in] solver s, atom r, intvar z, intvar x);
boolean int_max([in] solver s, atom r,
  intvar z, [in,size_is(sz)] intvar xs[], int sz);

boolean int_le([in] solver s, atom r, intvar z, intvar x, int k);
boolean int_ne([in] solver s, atom r, intvar z, intvar x);

boolean int_element([in] solver s, atom r,
  intvar z, intvar x, [in,size_is(sz)] int elts[], int sz);
boolean var_int_element([in] solver s, atom r,
  intvar z, intvar x, [in,size_is(sz)] intvar elts[], int sz);
